language: rust
rust:
        - nightly-2018-04-28
cache: cargo
env: NAME='cargo-travis'
sudo: required # travis-ci/travis-ci#9061
before_script:
        - cargo install cargo-travis || echo "cargo-travis already installed"
script:
        - |
                cargo build    --verbose &&
                cargo test     --verbose
after_success:
        - |
                cargo coverage --verbose &&
                bash <(curl -s https://codecov.io/bash) -s target/kcov
addons: # required for kcov
        apt:
                packages:
                        - libcurl4-openssl-dev
                        - libelf-dev
                        - libdw-dev
                        - binutils-dev
                        - cmake
