[package]
name = "device-checkout-rs"
version = "0.1.0"
authors = ["Toby Smith <toby@tismith.id.au>"]

[dependencies]
failure = "0.1.1"
log = "0.4.1"
stderrlog = "0.3.0"
clap = "2.31.2"
rocket = "0.3.8"
rocket_codegen = "0.3.8"
serde = "1.0"
serde_derive = "1.0"
serde_json = "1.0"

[dev-dependencies]
assert_cli = "0.5"

[dependencies.rocket_contrib]
version = "0.3.8"
default-features = false
features = ["json"]
