openapi: "3.0.2"
info:
  title: Device Checkout API documentation
  version: 0.1.0
paths:
  /api/reservations:
    post:
      description: Creates a reservation for a device that matches the parameters
      summary: Reserve device by params
      operationId: reserveDeviceByParams
      requestBody:
        description: Reservation to book
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/NewReservation'
            example:
                owner: Alice
                comment: Using to demonstrate API usage
                device:
                  sku: ED5000
      responses:
        '200':
          description: reservation response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Reservation'
              example:
                id: 1
                owner: Alice
                comment: Using to demonstrate API usage
                device:
                  id: 1
                  name: test-device-1
                  url: http://test-device.example-org
                  sku: ED5000

        default:
          description: unexpected error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
  /api/reservations/{id}:
    delete:
      description: End a reservation of a device
      summary: Return device
      operationId: deleteReservation
      parameters:
      - name: id
        in: path
        description: ID of reservation to end
        required: true
        schema:
          type: integer
          format: int32
      responses:
        '204':
          description: Reservation deleted
        '400':
          description: Reservation has already been ended
        '404':
          description: Cannot find reservation with given ID
        default:
          description: Unexpected error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
components:
  schemas:
    Reservation:
      allOf:
        - $ref: '#/components/schemas/NewReservation'
        - type: object
      required:
        - id
        - device
        - owner
      properties:
        id:
          type: integer
          format: int32
    NewReservation:
      type: object
      required:
        - owner
      properties:
        device:
          type: object
          $ref: '#/components/schemas/Device'
        owner:
          type: string
        comment:
          type: string
    Device:
      type: object
      properties:
        id:
          type: integer
          format: int32
        name:
          type: string
        url:
          type: string
        sku:
          type: string
    Error:
      type: object
      required:
        - code
        - message
      properties:
        code:
          type: integer
          format: int32
        message:
          type: string
